baseURL: https://modelica.org
title: Modelica
theme: ma-hugo-theme
params:
  logo: /images/ma-logos/dark/m-ball.svg
  favicon: /images/m-ball-favicon.svg
  darkMode: true
  email: board@modelica.org
  uacode: UA-145375737-1
  linkedin: modelica-association
  youtube: modelicaassociation
  x: modelica
menu:
  main:
    - pageRef: "language"
      identifier: "language"
      name: "Language"
      url: "/language/"
      weight: 1

    - pageRef: "association"
      identifier: "association"
      name: "Association"
      url: "/association/"
      weight: 1

    - pageRef: "community"
      identifier: "community"
      name: "Community"
      url: "/community/"
      weight: 2

    - pageRef: "consulting"
      identifier: "consulting"
      name: "Consulting"
      url: "/community/consulting/"
      parent: "community"
      weight: 1

    - pageRef: "development"
      identifier: "development"
      name: "Development"
      url: "/community/development/"
      parent: "community"
      weight: 2

    - pageRef: "projects"
      identifier: "projects"
      name: "Projects"
      url: "/community/projects/"
      parent: "community"
      weight: 3

    - pageRef: "training"
      identifier: "training"
      name: "Training"
      url: "/community/training/"
      parent: "community"
      weight: 4

    - pageRef: "usergroups"
      identifier: "usergroups"
      name: "Usergroups"
      url: "/community/usergroups/"
      parent: "community"
      weight: 5

    - pageRef: "events"
      identifier: "events"
      name: "Events"
      url: "/events/"
      weight: 4    

    - pageRef: "overview"
      identifier: "overview"
      name: "All Past and Upcoming Events"
      url: "/events/"
      parent: "events"
      weight: 1  

    - pageRef: "asian2026"
      identifier: "asian2026"
      name: "Asian Modelica & FMI Conference 2026"
      url: "/events/asian2026"
      parent: "events"
      weight: 2    

    - pageRef: "american2026"
      identifier: "american2026"
      name: "American Modelica & FMI Conference 2026"
      url: "/events/american2026"
      parent: "events"
      weight: 3    

    - pageRef: "newsletter"
      identifier: "newsletter"
      name: "Newsletter"
      url: "/newsletter/"
      weight: 4

    - pageRef: "publications"
      identifier: "publications"
      name: "Publications"
      url: "/publications/"
      weight: 3

    - pageRef: "books"
      identifier: "books"
      name: "Books"
      url: "/publications/books/"
      parent: "publications"
      weight: 1

    - pageRef: "proceedings"
      identifier: "proceedings"
      name: "Proceedings"
      url: "/publications/proceedings/"
      parent: "publications"
      weight: 2

    - pageRef: "libraries"
      identifier: "libraries"
      name: "Libraries"
      url: "/libraries/"
      weight: 1

    - pageRef: "tools"
      identifier: "tools"
      name: "Tools"
      url: "/tools/"
      weight: 1
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 3
